#include "types.hpp"

string_map mod_map;

void initialise_mod_map()
{
	mod_map["ac"] = "Defense";
	mod_map["ac-miss"] = "Defense vs. Missile";
	mod_map["ac-hth"] = "Defense vs. Melee";
	mod_map["red-dmg"] = "Damage Reduction";
	mod_map["red-dmg%"] = "Damage Reduction (Percent)";
	mod_map["ac%"] = "Enhanced Defense";
	mod_map["red-mag"] = "Magic Damage Reduction";
	mod_map["str"] = "Strength";
	mod_map["dex"] = "Dexterity";
	mod_map["vit"] = "Vitality";
	mod_map["enr"] = "Energy";
	mod_map["mana"] = "Mana";
	mod_map["mana%"] = "Mana (Percent)";
	mod_map["hp"] = "Life";
	mod_map["hp%"] = "Life (Percent)";
	mod_map["att"] = "Attack Rating";
	mod_map["block"] = "Increased Blocking, Faster Block Rate";
	mod_map["cold-min"] = "Minimum Cold Damage";
	mod_map["cold-max"] = "Maximum Cold Damage";
	mod_map["cold-len"] = "Cold Damage length";
	mod_map["fire-min"] = "Minimum Fire Damage";
	mod_map["fire-max"] = "Maximum Fire Damage";
	mod_map["ltng-min"] = "Minimum Lightning Damage";
	mod_map["ltng-max"] = "Maximum Lightning Damage";
	mod_map["pois-min"] = "Minimum Poison Damage";
	mod_map["pois-max"] = "Maximum Poison Damage";
	mod_map["pois-len"] = "Poison Damage Length";
	mod_map["dmg-min"] = "Minimum Damage";
	mod_map["dmg-max"] = "Maximum Damage";
	mod_map["dmg%"] = "Enhanced Damage";
	mod_map["dmg-to-mana"] = "Damage to Mana";
	mod_map["res-fire"] = "Fire Resistance";
	mod_map["res-fire-max"] = "Maximum Fire Resistance";
	mod_map["res-ltng"] = "Lightning Resistance";
	mod_map["res-ltng-max"] = "Maximum Lightning Resistance";
	mod_map["res-cold"] = "Cold Resistance";
	mod_map["res-cold-max"] = "Maximum Cold Resistance";
	mod_map["res-mag"] = "Magic Resistance";
	mod_map["res-mag-max"] = "Maximum Magic Resistance";
	mod_map["res-pois"] = "Poison Resistance";
	mod_map["res-pois-max"] = "Maximum Poison Resistance";
	mod_map["res-all"] = "All Resistances";
	mod_map["res-all-max"] = "Maximum All Resistances";
	mod_map["abs-fire%"] = "Fire Absorption (Percent)";
	mod_map["abs-fire"] = "Fire Absorption";
	mod_map["abs-ltng%"] = "Lightning Absorption (Percent)";
	mod_map["abs-ltng"] = "Lightning Absorption";
	mod_map["abs-mag%"] = "Magic Absorption (Percent)";
	mod_map["abs-mag"] = "Magic Absorption";
	mod_map["abs-cold%"] = "Cold Absorption (Percent)";
	mod_map["abs-cold"] = "Cold Absorption";
	mod_map["dur"] = "Durability";
	mod_map["dur%"] = "Enhanced Durability";
	mod_map["regen"] = "Replenish Life";
	mod_map["thorns"] = "Attacker Takes Damage";
	mod_map["swing1"] = "Increased Attack Speed";
	mod_map["swing2"] = "Increased Attack Speed";
	mod_map["swing3"] = "Increased Attack Speed";
	mod_map["gold%"] = "Extra Gold";
	mod_map["mag%"] = "Better Chance of Getting Magic Item";
	mod_map["knock"] = "Knockback";
	mod_map["regen-stam"] = "Regenerate Stamina";
	mod_map["regen-mana"] = "Regenerate Mana";
	mod_map["stam"] = "Stamina";
	mod_map["time"] = "Time"; //unused
	mod_map["manasteal"] = "Mana Stolen Per Hit";
	mod_map["lifesteal"] = "Life Stolen Per Hit";
	mod_map["ama"] = "Amazon Skills";
	mod_map["pal"] = "Paladin Skills";
	mod_map["nec"] = "Necromancer Skills";
	mod_map["sor"] = "Sorceress Skill";
	mod_map["bar"] = "Barbarian";
	mod_map["herb"] = "Herb"; //unused
	mod_map["light"] = "Light Radius";
	mod_map["color"] = "Colour"; //unused
	mod_map["ease"] = "Requirements";
	mod_map["move1"] = "Faster Run/Walk";
	mod_map["move2"] = "Faster Run/Walk";
	mod_map["move3"] = "Faster Run/Walk";
	mod_map["balance1"] = "Faster Hit Recovery";
	mod_map["balance2"] = "Faster Hit Recovery";
	mod_map["balance3"] = "Faster Hit Recovery";
	mod_map["block1"] = "Increased Blocking, Faster Block Rate";
	mod_map["block2"] = "Increased Blocking, Faster Block Rate";
	mod_map["block3"] = "Increased Blocking, Faster Block Rate";
	mod_map["cast1"] = "Faster Cast Rate";
	mod_map["cast2"] = "Faster Cast Rate";
	mod_map["cast3"] = "Faster Cast Rate";
	mod_map["res-pois-len"] = "Poison Length Reduction";
	mod_map["dmg"] = "Adds Damage";
	mod_map["howl"] = "Hit Causes Monster To Flee";
	mod_map["stupidity"] = "Hit Blinds Target";
	mod_map["ignore-ac"] = "Ignore Target's Defense";
	mod_map["reduce-ac"] = "Target Defense Reduction (Percent)";
	mod_map["noheal"] = "Prevent Monster Heal";
	mod_map["half-freeze"] = "Half Freeze Duration";
	mod_map["att%"] = "Bonus to Attack Rating";
	mod_map["dmg-ac"] = "Monster Defense Reduction per Hit";
	mod_map["dmg-demon"] = "Damage To Demons";
	mod_map["dmg-undead"] = "Damage To Undead";
	mod_map["att-demon"] = "Attack Rating Against Demons";
	mod_map["att-undead"] = "Attack Rating Against Undead";
	mod_map["throw"] = "Throw"; //unused
	mod_map["fireskill"] = "Fire Skills";
	mod_map["allskills"] = "All Skills";
	mod_map["light-thorns"] = "Attacker Takes Lightning Damage";
	mod_map["freeze"] = "Freezes Target";
	mod_map["openwounds"] = "Open Wounds";
	mod_map["crush"] = "Crushing Blow";
	mod_map["kick"] = "Kick"; //unused
	mod_map["mana-kill"] = "Mana After Each Kill";
	mod_map["demon-heal"] = "Life After Each Demon Kill";
	mod_map["bloody"] = "Bloody"; //unknown, Stormguild and Gorefoot have this
	mod_map["deadly"] = "Deadly Strike";
	mod_map["slow"] = "Slows Down Target";
	mod_map["nofreeze"] = "Cannot Be Frozen";
	mod_map["stamdrain"] = "Slow Stamina Drain";
	mod_map["reanimate"] = "Reanimation";
	mod_map["pierce"] = "Piercing Attack";
	mod_map["magicarrow"] = "Fires Magic Arrows";
	mod_map["explosivearrow"] = "Fires Explosive Arrows";

	//expansion
	mod_map["dru"] = "Druid Skills";
	mod_map["ass"] = "Assassin Skills";
	mod_map["skill"] = "Skill";
	mod_map["skilltab"] = "Skill Tab";
	mod_map["aura"] = "Aura";
	mod_map["att-skill"] = "Skill On Attack";
	mod_map["hit-skill"] = "Skill On Striking";
	mod_map["gethit-skill"] = "Skill When Struck";
	mod_map["sock"] = "Add Sockets";
	mod_map["dmg-fire"] = "Adds Fire Damage";
	mod_map["dmg-ltng"] = "Adds Lightning Damage";
	mod_map["dmg-mag"] = "Adds Magical Damage";
	mod_map["dmg-cold"] = "Adds Cold Damage";
	mod_map["dmg-pois"] = "Adds Poison Damage";
	mod_map["dmg-throw"] = "Adds Throw Damage"; //unused
	mod_map["dmg-norm"] = "Adds Damage";
	mod_map["ac/lvl"] = "Defense Per Level";
	mod_map["ac%/lvl"] = "Enhanced Defense Per Level";
	mod_map["hp/lvl"] = "Life Per Level";
	mod_map["mana/lvl"] = "Mana Per Level";
	mod_map["dmg/lvl"] = "Damage Per Level";
	mod_map["dmg%/lvl"] = "Enhanced Damage Per Level";
	mod_map["str/lvl"] = "Strength Per Level";
	mod_map["dex/lvl"] = "Dexterity Per Level";
	mod_map["enr/lvl"] = "Energy Per Level";
	mod_map["vit/lvl"] = "Vitality Per Level";
	mod_map["att/lvl"] = "Attack Rating Per Level";
	mod_map["att%/lvl"] = "Bonus To Attack Rating per Level";
	mod_map["dmg-cold/lvl"] = "Cold Damage Per Level";
	mod_map["dmg-fire/lvl"] = "Fire Damage Per Level";
	mod_map["dmg-ltng/lvl"] = "Lightning Damage Per Level";
	mod_map["dmg-pois/lvl"] = "Poison Damage Per Level";
	mod_map["res-cold/lvl"] = "Cold Resistance Per Level";
	mod_map["res-fire/lvl"] = "Fire Resistance Per Level";
	mod_map["res-ltng/lvl"] = "Lightning Resistance Per Level";
	mod_map["res-pois/lvl"] = "Poison Resistance Per Level";
	mod_map["abs-cold/lvl"] = "Cold Absorption Per Level";
	mod_map["abs-fire/lvl"] = "Fire Absorption Per Level";
	mod_map["abs-ltng/lvl"] = "Lightning Absorption Per Level";
	mod_map["abs-pois/lvl"] = "Poison Absorption Per Level";
	mod_map["thorns/lvl"] = "Attacker Takes Damage Per Level";
	mod_map["gold%/lvl"] = "Extra Gold Per Level";
	mod_map["mag%/lvl"] = "Better Chance of Getting Magic Item Per Level";
	mod_map["regen-stam/lvl"] = "Stamina Regeneration Per Level";
	mod_map["stam/lvl"] = "Stamina Per Level";
	mod_map["dmg-dem/lvl"] = "Damage To Demons Per Level";
	mod_map["dmg-und/lvl"] = "Damage To Undead Per Level";
	mod_map["att-dem/lvl"] = "Attack Rating Against Demons Per Level";
	mod_map["att-und/lvl"] = "Attack Rating Against Undead Per Level";
	mod_map["crush/lvl"] = "Crushing Blow Per Level";
	mod_map["wounds/lvl"] = "Open Wounds Per Level";
	mod_map["kick/lvl"] = "Kick Per Level"; //unused
	mod_map["deadly/lvl"] = "Deadly Strike Per Level";
	mod_map["gems%/lvl"] = "Gems Per Level"; //unused
	mod_map["rep-dur"] = "Repairs Durability";
	mod_map["rep-quant"] = "Replenishes Quantity";
	mod_map["stack"] = "Increased Stack Size";

	//all /time are unused
	mod_map["ac/time"] = "Defense Per Time"; //used by of Dawn
	mod_map["ac%/time"] = "Enhanced Defense Per Time";
	mod_map["hp/time"] = "Life Per Time";
	mod_map["mana/time"] = "Mana per Time";
	mod_map["dmg/time"] = "Damage Per Time";
	mod_map["dmg%/time"] = "Enhanced Damage Per Time";
	mod_map["str/time"] = "Strength Per Time";
	mod_map["dex/time"] = "Dexterity Per Time";
	mod_map["enr/time"] = "Energy Per Time";
	mod_map["vit/time"] = "Vitality Per Time";
	mod_map["att/time"] = "Attack Rating Per Time";
	mod_map["att%/time"] = "Bonus To Attack Rating Per Time";
	mod_map["dmg-cold/time"] = "Cold Damage Per Time";
	mod_map["dmg-fire/time"] = "Fire Damage Per Time";
	mod_map["dmg-ltng/time"] = "Lightning Damage Per Time";
	mod_map["dmg-pois/time"] = "Poison Damage Per Time";
	mod_map["res-cold/time"] = "Cold Resistance Per Time";
	mod_map["res-fire/time"] = "Fire Resistance Per Time";
	mod_map["res-ltng/time"] = "Lightning Resistance Per Time";
	mod_map["res-pois/time"] = "Poison Resistance Per Time";
	mod_map["abs-cold/time"] = "Cold Absorption Per Time";
	mod_map["abs-fire/time"] = "Fire Absorption Per Time";
	mod_map["abs-ltng/time"] = "Lightning Absorption Per Time";
	mod_map["abs-pois/time"] = "Poison Absorption Per Time";
	mod_map["gold%/time"] = "Extra Gold Per Time";
	mod_map["mag%/time"] = "Better Chance Of Getting Magic Item Per Time";
	mod_map["regen-stam/time"] = "Stamina Regeneration Per Time";
	mod_map["stam/time"] = "Stamina Per Time";
	mod_map["dmg-dem/time"] = "Damage To Demons Per Time";
	mod_map["dmg-und/time"] = "Damage To Undead Per Time";
	mod_map["att-dem/time"] = "Attack Rating Against Demons Per Time";
	mod_map["att-und/time"] = "Attack Rating Against Undead Per Time";
	mod_map["crush/time"] = "Crush Damage Per Time";
	mod_map["wounds/time"] = "Open Wounds Per Time";
	mod_map["kick/time"] = "Kick Damage Per Time";
	mod_map["deadly/time"] = "Deadly Strike Per Time";

	mod_map["pierce-fire"] = "Decreases Enemy Fire Resistance";
	mod_map["pierce-ltng"] = "Decreases Enemy Lightning Resistance";
	mod_map["pierce-cold"] = "Decreases Enemy Cold Resistance";
	mod_map["pierce-pois"] = "Decreases Enemy Poison Resistance";
	mod_map["indestruct"] = "Indestructible";
	mod_map["extra-fire"] = "Fire Skill Damage";
	mod_map["extra-ltng"] = "Lightning Skill Damage";
	mod_map["extra-cold"] = "Cold Skill Damage";
	mod_map["extra-pois"] = "Poison Skill Damage";
	mod_map["dmg-elem"] = "Adds Elemental Damage";
	mod_map["dmg-elem-min"] = "Minimum Elemental Damage";
	mod_map["dmg-elem-max"] = "Maximum Elemental Damage";
	mod_map["all-stats"] = "All Attributes";
	mod_map["heal-kill"] = "Life After Each Kill";
	mod_map["cheap"] = "Reduces All Vendor Prices";
	mod_map["rip"] = "Slain Monsters Rest In Peace";
	mod_map["att-mon%"] = "Bonus To Attack Rating Against Monsters"; //unused
	mod_map["dmg-mon%"] = "Damage To Monsters"; //unused
	mod_map["kill-skill"] = "Skill On Kill";
	mod_map["death-skill"] = "Skill On Death";
	mod_map["levelup-skill"] = "Skill On Levelup";
	mod_map["skill-rand"] = "Random Skill";
	mod_map["fade"] = "Fade";
	mod_map["levelreq"] = "Decreased Level Requirement";
	mod_map["ethereal"] = "Ethereal";
	mod_map["oskill"] = "Adds Special Skill";

	mod_map["charged"] = "Charges";

	//hack for typo
	mod_map["Light"] = "Add Light Radius";

	//new stuff
	mod_map["addxp"] = "Experience Bonus";
	mod_map["randclassskill"] = "Random Class Skill Bonus";
}
